services:
  andcool_site:
    container_name: andcool_site
    ports:
      - "4000:4000"
    build: 
      context: ./
      dockerfile: Dockerfile
    command: npm run start
    restart: unless-stopped